SET REFERENTIAL_INTEGRITY FALSE;

TRUNCATE TABLE film_likes;
TRUNCATE TABLE film_genre;
TRUNCATE TABLE user_friends;
TRUNCATE TABLE film;
TRUNCATE TABLE users;
TRUNCATE TABLE genre;
TRUNCATE TABLE MPA;

ALTER TABLE users ALTER COLUMN id RESTART WITH 1;
ALTER TABLE film ALTER COLUMN id RESTART WITH 1;
ALTER TABLE genre ALTER COLUMN id RESTART WITH 1;
ALTER TABLE mpa ALTER COLUMN id RESTART WITH 1;

SET REFERENTIAL_INTEGRITY TRUE;

MERGE INTO MPA KEY(id) VALUES (1, 'G');
MERGE INTO MPA KEY(id) VALUES (2, 'PG');
MERGE INTO MPA KEY(id) VALUES (3, 'PG-13');
MERGE INTO MPA KEY(id) VALUES (4, 'R');
MERGE INTO MPA KEY(id) VALUES (5, 'NC-17');

MERGE INTO genre KEY(id) VALUES (1, 'Комедия');
MERGE INTO genre KEY(id) VALUES (2, 'Драма');
MERGE INTO genre KEY(id) VALUES (3, 'Мультфильм');
MERGE INTO genre KEY(id) VALUES (4, 'Триллер');
MERGE INTO genre KEY(id) VALUES (5, 'Документальный');
MERGE INTO genre KEY(id) VALUES (6, 'Боевик');